### PR TITLE
Add prettier workflow

### PR DESCRIPTION
**Pull request by ericanderson**
## :recycle: Current situation

I noticed it was difficult to maintain consistent formatting in some of the repos. 

## :bulb: Proposed solution

Follow practices of many many other repos by using prettier to ensure consistency.

## :gear: Release Notes

* Prettier is now available as a required step for PRs.

## :heavy_plus_sign: Additional Information
n/a

### Testing

n/a

### Reviewer Nudging

n/a

### CODE REVIEW

**Comment by Supereg** [comment]
Thanks for the contribution though we already have a global workflow for the `lint` command/script. It is located here: https://github.com/homebridge/.github/blob/a29f84d4e22b3222d8855079f535e303a19a3eae/.github/workflows/eslint.yml.

All the core homebridge projects are equipped with `eslint`.

**Comment by ericanderson** [comment]
Are you suggesting you don't want prettier or that I should just use the lint command to add the check?

**Comment by Supereg** [comment]
> Are you suggesting you don't want prettier or that I should just use the lint command to add the check?

First of all yes, we already have the `lint` script set up in the above-linked workflow. This PR would only duplicate that.
And secondly, all projects which do implement the`lint` script use `eslint` instead of `prettier` and we have no desire to change that.

**Comment by ericanderson** [comment]
Cool, np

**Pull request closed without merging**
